version: '3.3'

services:
  influx_updater:
    container_name_legacy: influx_updater_legacy
    build: ./influx_updater_legacy
    command: sh -c "dockerize -wait tcp://db:5432 python influx_updater_legacy.py"
    restart: unless-stopped
    volumes:
      - ./influx_updater_legacy:/app
    env_file:
      - ./config/.env
    depends_on:
      - db
      - influx
      - grafana
      - virtual_modbustcp
    networks:
      - default_network 

  db:
    container_name: default_db
    image: postgres:12.0
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./config/registers.csv:/data/registers.csv
      - ./config/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./config/.env
    networks:
      - default_network

  influx:
    container_name: influx_db
    image: influxdb:1.8.0
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    env_file:
      - ./config/.env
    networks:
      - default_network

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./config/.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - default_network

  virtual_modbustcp:
    container_name: virtual_tlc10000_server
    build: ./virtual_tlc10000_server
    command: python -u virtual_tlc10000_server.py
    ports:
      - 502:502
    env_file:
      - ./config/.env
    networks:
      - default_network

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:

networks:
  default_network:
    driver: bridge