{
 "title": "Gospodarstwo Domowe - Bilans Energetyczny",
 "time": { "from": "now-21d", "to": "now-14d" },
 "panels": [
  {
   "title": "Moc Oddawana Licznik Główny",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT abs(last(\"value\") / 1000) FROM \"activePower\" WHERE (\"description\" = 'main_energy_meter') AND value < 0 AND time > now() - 5m\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Moc Pobierana Licznik Główny",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT last(\"value\") / 1000 FROM \"activePower\" WHERE (\"description\" = 'main_energy_meter') AND value > 0 AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Moc Oddawana Falownik",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Moc Falownik",
     "measurement": "activePower",
     "query": "SELECT last(\"value\") FROM \"activePower\" WHERE (\"description\" = 'inverter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Moc Pobierana Dom",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Moc Dom",
     "measurement": "activePower",
     "query": "SELECT last(\"value\") / 1000 FROM \"activePower\" WHERE (\"description\" = 'house_energy_meter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "house_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Moc Pobierana Pompa Ciepła",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Moc Pompa Ciepła",
     "measurement": "activePower",
     "query": "SELECT last(\"value\") FROM \"activePower\" WHERE (\"description\" = 'hp_energy_meter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "hp_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Moc Pobierana Ładowanie EV",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Moc Stacja Ładowania EV",
     "measurement": "activePower",
     "query": "SELECT last(\"value\") / 1000 FROM \"activePower\" WHERE (\"description\" = 'charger_energy_meter') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "charger_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Oddana Licznik Głowny",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyProduced\" WHERE (\"description\" = 'main_energy_meter') AND $timeFilter GROUP BY time(1h) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Pobrana Licznik Głowny",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'main_energy_meter') AND $timeFilter GROUP BY time(1h) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Wyprodukowana Falownik",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyProducedToday\" WHERE (\"description\" = 'inverter') AND $timeFilter GROUP BY time(1h) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Pobrana Dom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'house_energy_meter') AND $timeFilter GROUP BY time(1h) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Pobrana PC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'hp_energy_meter') AND $timeFilter GROUP BY time(1h) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Energia Pobrana Ładowanie EV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "measurement": "activePower",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'charger_energy_meter') AND $timeFilter GROUP BY time(1h) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Bilans Energetyczny Bezwzględny",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Energia Zużyta Dom",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'house_energy_meter') AND $timeFilter GROUP BY time(1h) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "house_energy_meter" }
     ]
    },
    {
     "alias": "Energia Zużyta Pompa Ciepła",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "hp_energy_meter" }
     ]
    },
    {
     "alias": "Energia Wyprodukowana Falownik",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyProducedToday",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyProducedToday\" WHERE (\"description\" = 'inverter') AND $timeFilter GROUP BY time(1h) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "inverter" }
     ]
    },
    {
     "alias": "Energia Zużyta Stacja Ładowania",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'house_energy_meter') AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "charger_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Bilans Energetyczny Licznik Główny",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Energia Zużyta",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'main_energy_meter') AND $timeFilter GROUP BY time(1h) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    },
    {
     "alias": "Energia Wyprodukowana",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyProduced",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyProduced\" WHERE (\"description\" = 'main_energy_meter') AND $timeFilter GROUP BY time(1h) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Bilans Energetyczny Dzienny Bezwzględny",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Energia Zużyta Dom",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyConsumed\" WHERE (\"description\" = 'house_energy_meter') AND $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "house_energy_meter" }
     ]
    },
    {
     "alias": "Energia Zużyta Pompa Ciepła",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "hp_energy_meter" }
     ]
    },
    {
     "alias": "Energia Wyprodukowana Falownik",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyProducedToday",
     "query": "SELECT sum(non_negative_difference(\"value\")) FROM \"activeEnergyProducedToday\" WHERE (\"description\" = 'inverter') AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "inverter" }
     ]
    },
    {
     "alias": "Energia Zużyta Stacja Ładowania EV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "charger_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Bilans Energetyczny Dzienny Licznik Główny",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Energia Zużyta",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyConsumed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    },
    {
     "alias": "Energia Wyprodukowana",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activeEnergyProduced",
     "query": "SELECT non_negative_difference(max(\"value\")) FROM \"activeEnergyProduced\" WHERE (\"description\" = 'main_energy_meter') AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Moc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Moc Licznik Główny",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "activePower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    },
    {
     "alias": "Moc Falownik",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "activePower",
     "query": "SELECT mean(\"value\") FROM \"activePower\" WHERE (\"description\" = 'inverter') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "inverter" }
     ]
    },
    {
     "alias": "Moc Dom",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "activePower",
     "query": "SELECT mean(\"value\") / 1000 FROM \"activePower\" WHERE (\"description\" = 'house_energy_meter') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "house_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Napięcie przyłącza",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Napięcie L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "voltageL1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    },
    {
     "alias": "Napięcie L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "voltageL2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    },
    {
     "alias": "Napięcie L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "voltageL3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Napięcie L1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Napięcie L1",
     "measurement": "voltageL1",
     "query": "SELECT last(\"value\")  FROM \"volatgeL1\" WHERE (\"description\" = 'main_energy_meter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Napięcie L2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Napięcie L2",
     "measurement": "voltageL2",
     "query": "SELECT last(\"value\")  FROM \"volatgeL1\" WHERE (\"description\" = 'main_energy_meter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  },
  {
   "title": "Napięcie L3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Napięcie L3",
     "measurement": "voltageL3",
     "query": "SELECT last(\"value\")  FROM \"volatgeL1\" WHERE (\"description\" = 'main_energy_meter') AND time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "description", "operator": "=", "value": "main_energy_meter" }
     ]
    }
   ]
  }
 ]
}