# config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influx_db:8086
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: admin
    database: influx_default
    jsonData:
      httpMode: GET