# Generated by Django 3.1.2 on 2020-10-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(max_length=32)),
                ('register_address', models.PositiveIntegerField()),
                ('measurement_name', models.CharField(max_length=64)),
                ('data_unit', models.CharField(blank=True, max_length=8, null=True)),
                ('data_type', models.PositiveIntegerField(choices=[(1, 'INT'), (2, 'LONG'), (3, 'FLOAT')])),
                ('function_code', models.PositiveIntegerField(choices=[(3, 'READ_HOLDING_REGISTERS'), (4, 'READ_INPUT_REGISTERS')])),
                ('word_order', models.PositiveIntegerField(choices=[(1, 'LITTLE'), (2, 'BIG')])),
                ('byte_order', models.PositiveIntegerField(choices=[(1, 'LITTLE'), (2, 'BIG')])),
            ],
            options={
                'unique_together': {('meter_type', 'measurement_name')},
            },
        ),
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(max_length=32)),
                ('host', models.TextField(max_length=64)),
                ('port', models.PositiveIntegerField()),
                ('slave_address', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=128, null=True)),
            ],
            options={
                'unique_together': {('host', 'port', 'slave_address')},
            },
        ),
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_trigger', models.CharField(default=None, max_length=4)),
                ('minute_trigger', models.CharField(default=None, max_length=4)),
                ('second_trigger', models.CharField(default=None, max_length=4)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_api.energymeter')),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_api.register')),
            ],
            options={
                'unique_together': {('meter_id', 'register_id')},
            },
        ),
    ]
