# Generated by Django 3.1.2 on 2020-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='hour_trigger',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='minute_trigger',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='second_trigger',
            field=models.CharField(default='15', max_length=4),
        ),
    ]
